name: CI

on:
  push:
    branches:
      - add-ci-pipeline

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.ppk
        chmod 600 private_key.ppk
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AZURE_VM_SSH_KEY_FRONTEND_PPK }}

    - name: Copy files via SCP
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.ppk -r ./dist/* ${{ secrets.AZURE_USER_ID }}@${{ secrets.AZURE_VM_IP_FRONTEND }}:/usr/src/app

    - name: SSH and restart service
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.ppk ${{ secrets.AZURE_USER_ID }}@${{ secrets.AZURE_VM_IP_FRONTEND }} << 'EOF'
          pm2 restart all
        EOF
