name: Frontend_Build_and_Deploy

on:
  push:
    branches:
      - build_and_deploy

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.ANSIBLE_SSH_CONVERTED }}" > private_key
          chmod 600 private_key
          ls -l private_key

      - name: Test SSH connection to Ansible controller
        run: |
          ssh -o StrictHostKeyChecking=accept-new -i ./private_key ${{ secrets.AZURE_USER_ID }}@${{ secrets.Ansible_Controller_IP }} "echo SSH connection successful"

      - name: Deploy and configure VM on Azure
        run: |
          ssh -o StrictHostKeyChecking=accept-new -i ./private_key ${{ secrets.AZURE_USER_ID }}@${{ secrets.Ansible_Controller_IP }} << 'EOF'
            set -e

            # Login to Azure
            az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
            
            # Create the VM
            az vm create --resource-group B2C6A --name frontendvm4 \
              --image "Canonical:0001-com-ubuntu-minimal-jammy:minimal-22_04-lts-gen2:latest" \
              --admin-username ${{ secrets.AZURE_USER_ID }} --assign-identity --generate-ssh-keys \
              --public-ip-sku Standard --location westeurope --size Standard_B1s \
              --storage-sku Standard_LRS --nic-delete-option delete --os-disk-delete-option delete
              
            # Open the port
            az vm open-port --resource-group B2C6A --name frontendvm3 --port 3000 --priority 1100

            # Wait for the VM to be ready
            sleep 120
            
            # Get the VM's public IP address
            vm_ip=$(az vm list-ip-addresses --resource-group B2C6A --name frontendvm3 --query "[].virtualMachine.network.publicIpAddresses[].ipAddress" -o tsv)
            echo "VM IP Address: $vm_ip"

            # SSH into the new VM and run setup tasks
            ssh -o StrictHostKeyChecking=accept-new -i /home/${{ secrets.AZURE_USER_ID }}/.ssh/id_rsa ${{ secrets.AZURE_USER_ID }}@$vm_ip << 'VM_EOF'
              sudo apt-get update
              sudo apt-get install -y git curl
              curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
              sudo apt-get install -y nodejs

              mkdir -p /home/${{ secrets.AZURE_USER_ID }}/backup
              git clone https://github.com/ZuydUniversity/B2C6_B2A_Frontend /home/${{ secrets.AZURE_USER_ID }}/backup/B2C6_B2A_Frontend
              
              cd /home/${{ secrets.AZURE_USER_ID }}/backup/B2C6_B2A_Frontend
              npm install
              npm run dev
              VM_EOF
            EOF
