name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: frontend-build
        path: |
          dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_USER_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }}

    - name: Start Ansible controller VM
      run: az vm start --resource-group B2C6A --name ansible-controller

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install ansible -y

    - name: Copy Ansible inventory
      run: echo "[frontend]\nfrontend.example.com" > inventory.ini

    - name: Run Ansible playbook
      run: ansible-playbook -i inventory.ini deploy_frontend.yml
